### ISSUE TITLE
1차 스프린트 이후 리팩토링

### ISSUE THREAD

**Issue by HiimKwak** [hufs-sports-live/client#17]
### UI
  - 좌우 여백
### 메인페이지
   - 각 경기 상태 영역에 아무런 컴포넌트가 없을 경우 '해당하는 경기가 없음'을 알리는 default UI 필요
   - 예정 카테고리 게임들: 시간 표현 불안요소 제거 필요
   - 추후 축구 뿐만 아니라 다양한 종목의 스포츠가 추가될 경우를 대비할 필요가 있어보임!
### 로그인페이지
  - UI
  - 로컬스토리지에 토큰 저장하는 로직의 불안성 제거 필요(저는 잘 모르긴 해서 알려주세요 ㅎ)
  - 관리자 인증을 받았을 땐 헤더가 푸른색으로 바뀐다든지 하는 구분 요소가 있으면 좋긴 할듯?
### /admin
  - UI
  - (개인적 생각) 경기 추가 페이지를 독립적으로 빼기 보다 추후 메인 페이지 헤더에 버튼-팝업 형식으로 inline하게 바꾸면 좋을 것 같다는 생각
### 상세 페이지
   - UI
     - 게임 타임라인: 득점자의 팀명까지 바인딩해 보여주기
     - 게임 타임라인: 득점 기록의 시간을 카드 바깥 왼쪽 상단으로 빼는게 더 직관적일 것 같다는 생각
     - 댓글 영역: 응원 팀을 고르고 댓글 작성할 수 있게 하면 좋을 듯
     - 관리자 접근: 수정 버튼들 직관적으로 정리하기
     - 경기 유튜브 영상 영역 제작 필요
### /detail/[id]/modify , /detail/[id]/status
  - 둘 다 메인페이지와 같이 버튼-팝업 형태로 제작하면 훨씬 깔끔할듯?

**Comment by HiimKwak** [comment]
### 메인페이지
   - 각 경기 상태 영역에 아무런 컴포넌트가 없을 경우 '해당하는 경기가 없음'을 알리는 default UI 필요
   - 예정 카테고리 게임들: 시간 표현 불안요소 제거 필요
   - 추후 축구 뿐만 아니라 다양한 종목의 스포츠가 추가될 경우를 대비할 필요가 있어보임!

**Comment by HiimKwak** [comment]
### 로그인페이지
  - UI
  - 로컬스토리지에 토큰 저장하는 로직의 불안성 제거 필요(저는 잘 모르긴 해서 알려주세요 ㅎ)
  - 관리자 인증을 받았을 땐 헤더가 푸른색으로 바뀐다든지 하는 구분 요소가 있으면 좋긴 할듯?

**Comment by HiimKwak** [comment]
### /admin
  - UI
  - (개인적 생각) 경기 추가 페이지를 독립적으로 빼기 보다 추후 메인 페이지 헤더에 버튼-팝업 형식으로 inline하게 바꾸면 좋을 것 같다는 생각

**Comment by HiimKwak** [comment]
### 상세 페이지
   - UI
     - 게임 타임라인: 득점자의 팀명까지 바인딩해 보여주기
     - 게임 타임라인: 득점 기록의 시간을 카드 바깥 왼쪽 상단으로 빼는게 더 직관적일 것 같다는 생각
     - 댓글 영역: 응원 팀을 고르고 댓글 작성할 수 있게 하면 좋을 듯
     - 관리자 접근: 수정 버튼들 직관적으로 정리하기
     - 경기 유튜브 영상 영역 제작 필요

**Comment by HiimKwak** [comment]
### /detail/[id]/modify , /detail/[id]/status
  - 둘 다 메인페이지와 같이 버튼-팝업 형태로 제작하면 훨씬 깔끔할듯?

**Comment by HiimKwak** [comment]
> ### /detail/[id]/modify , /detail/[id]/status
> * 둘 다 메인페이지와 같이 버튼-팝업 형태로 제작하면 훨씬 깔끔할듯?

이거 관련해서 RadixUI란 UI 라이브러리 도입을 적극적으로 추진하고자 합니다.

## RadixUI가 뭔가요?

- 유튜브 튜토리얼(20분 3부작)
[Styling a Radix Dialog with Tailwind CSS](https://www.youtube.com/watch?v=KvZoBV_1yYE&t=0s)
- [튜토리얼 따라한 내 개인 레포](https://github.com/HiimKwak/RadixUI-playground/blob/main/radix-dialog-tutorial/app/page.tsx)

핵심부터 먼저 이야기하자면 RadixUI는 UI 라이브러리로 딱히 프로젝트 코드 퀄리티에 큰 영향을 미치지 않으면서 필요한 부분에만 독립적으로 삽입할 수 있는 UI 컴포넌트 모음집입니다.

제가 말한 버튼-팝업 컴포넌트는 아래와 같이 동작합니다.
```tsx
import * as Dialog from "@radix-ui/react-dialog";

<Dialog.Portal>
  <Dialog.Overlay className="fixed inset-0 bg-black/50 data-[state=open]:animate-[dialog-overlay-show_200ms] data-[state=closed]:animate-[dialog-overlay-hide_200ms]" />
  <Dialog.Content className="fixed w-full max-w-md p-8 text-gray-900 -translate-x-1/2 -translate-y-1/2 bg-white rounded-md shadow left-1/2 top-1/2 data-[state=open]:animate-[dialog-content-show_200ms] data-[state=closed]:animate-[dialog-content-hide_200ms]">
    <div className="flex items-center justify-between">
      <Dialog.Title className="text-xl">{title}</Dialog.Title>
      <Dialog.Close className="text-gray-400 hover:text-gray-500">
        <Cross1Icon />
      </Dialog.Close>
    </div>
    {children}
  </Dialog.Content>
</Dialog.Portal>
```
`Dialog` 모듈을 불러오고, 각각 모달(또는 버튼)의 검은 배경의 `Overlay`, 모달 그 자체인 `Content`와 하위 타이틀 `Title`, 축소 `Close` APi를 사용하면 됩니다. 이것들을 `Portal`로 감싸주면 RadixUI가 알아서 독립적인 div로 렌더링해주며, 개발자도구 > 요소를 눌러 확인해보면 DOM트리 중간에 생기는게 아니라 main과 동일한 레벨에 생겨 독립적으로 동작하도록 보장해줍니다(이건 정확하지 않을 수 있음).

이 `Dialog` 모듈을 그대로 사용해도 전혀 무방하지만, 링크에 나오는 유튜버 개발자는 `Modal` 컴포넌트로 다시 추상화를 한 번 더 해 사용성을 극대화시켰습니다. 마치 이번 성민이형이 Game 컴포넌트를 디자인한 방식처럼(Game Object에 매핑한 방식) 추상화가 이뤄졌습니다.

## Dialog -> Modal로 한 번 더 추상화하기

```tsx
import * as Dialog from "@radix-ui/react-dialog";
import { Cross1Icon } from "@radix-ui/react-icons";
import { ReactNode } from "react";

export default function Modal({
  open,
  onOpenChange,
  children,
}: {
  open?: boolean;
  onOpenChange?: (open: boolean) => void;
  children: ReactNode;
}) {
  return (
    <Dialog.Root open={open} onOpenChange={onOpenChange}>
      {children}
    </Dialog.Root>
  );
}

function ModalContent({
  title,
  children,
}: {
  title: string;
  children: ReactNode;
}) {
  return (
    <Dialog.Portal>
      <Dialog.Overlay className="fixed inset-0 bg-black/50 data-[state=open]:animate-[dialog-overlay-show_200ms] data-[state=closed]:animate-[dialog-overlay-hide_200ms]" />
      <Dialog.Content className="fixed w-full max-w-md p-8 text-gray-900 -translate-x-1/2 -translate-y-1/2 bg-white rounded-md shadow left-1/2 top-1/2 data-[state=open]:animate-[dialog-content-show_200ms] data-[state=closed]:animate-[dialog-content-hide_200ms]">
        <div className="flex items-center justify-between">
          <Dialog.Title className="text-xl">{title}</Dialog.Title>
          <Dialog.Close className="text-gray-400 hover:text-gray-500">
            <Cross1Icon />
          </Dialog.Close>
        </div>

        {children}
      </Dialog.Content>
    </Dialog.Portal>
  );
}

Modal.Button = Dialog.Trigger;
Modal.Content = ModalContent;
Modal.Close = Dialog.Close;
```
이 댓글에 위 유튜브 3부작 내용을 모두 이야기하기엔 지면이 좁기도 하고 저 또한 완전히 제 것이 아니기 때문에, 몇 가지 포인트만 말씀드리고 나머지는 유튜브 영상으로 대체하도록 하겠습니다. 2배속으로 재생하셔서 단순무식한 `data.map => li div button ~~` 컴포넌트가 마지막엔 디자인과 기능이 완전히 분리된 추상화 컴포넌트로 바뀌는 것을 꼭 보시기 바랍니다 ㅋㅋ

위처럼 모달 컴포넌트를 작성해주면 아래 스샷에 나온 것처럼 아주 직관적으로 사용이 가능합니다. css class만 작성해주면 기능은 알아서 다 처리해주죠.
![image](https://github.com/hufs-sports-live/client/assets/87803596/ee7b7ad6-769b-4ba2-b79e-cd7bb397a205) 

모달을 직접 만들려면 모달의 추상화 디자인 뿐만 아니라 정말 귀찮은 모달 토글 온오프 기능이나, 키보드로도 접근할 수 있게 하려면 별도의 키 매핑이 반드시 필요합니다. 이런 부분도 RadixUI 컴포넌트를 쓰면 무.료.로.해.줍.니.다. 정말 좋지 않나요?

마지막으로 Radix의 좋은 점에 대해 정리하고 말을 줄이겠습니다. 글이 너무 길다면 유튭 영상 3부작 2배속으로 제발 한 번만 봐주세요. ㅋㅋ 진짜 좋아서 그럼

## Radix의 좋은 점

1. Incremental adoption
   모듈을 각각 adopt해와 번들 사이즈를 줄일 수 있다.

2. Unstyled
   스타일은 없지만 Tag name으로 구분이 이미 돼있기 때문에 가독성이 매우 좋다

3. 키보드 상호작용 지원
   별도의 세팅 없이도 WAI-ARIA 패턴에 맞게 키보드액션이 다 매핑돼있다.

4. 각 모듈마다 필요한 구성요소들이 준비돼있다
   각 모듈마다 필요한 구성요소들이 이미 갖춰져있다. 모달의 경우 트리거(버튼), 포탈(모달) - 오버레이(검은화면), 컨텐트로 구성돼있고 심지어 오버레이를 갖다 쓰면 스크롤도 자동으로 막아준다!

5. Uncontrolled
   Radix Component들은 이미 그 내장 기능을 통해 개발자가 control하지 않아도 되는 상태이다(uncontrolled). 하지만 local state를 생성해 얼마든지 개발자가 control할 수 있는 자유도가 있다(개편함)

**Comment by seongminn** [comment]
> > ### /detail/[id]/modify , /detail/[id]/status
> > 
> > * 둘 다 메인페이지와 같이 버튼-팝업 형태로 제작하면 훨씬 깔끔할듯?
> 
> 이거 관련해서 RadixUI란 UI 라이브러리 도입을 적극적으로 추진하고자 합니다.
> 
> ## RadixUI가 뭔가요?
> * 유튜브 튜토리얼(20분 3부작)
>   [Styling a Radix Dialog with Tailwind CSS](https://www.youtube.com/watch?v=KvZoBV_1yYE&t=0s)
> * [튜토리얼 따라한 내 개인 레포](https://github.com/HiimKwak/RadixUI-playground/blob/main/radix-dialog-tutorial/app/page.tsx)
> 
> 핵심부터 먼저 이야기하자면 RadixUI는 UI 라이브러리로 딱히 프로젝트 코드 퀄리티에 큰 영향을 미치지 않으면서 필요한 부분에만 독립적으로 삽입할 수 있는 UI 컴포넌트 모음집입니다.
> 
> 제가 말한 버튼-팝업 컴포넌트는 아래와 같이 동작합니다.
> 
> ```tsx
> import * as Dialog from "@radix-ui/react-dialog";
> 
> <Dialog.Portal>
>   <Dialog.Overlay className="fixed inset-0 bg-black/50 data-[state=open]:animate-[dialog-overlay-show_200ms] data-[state=closed]:animate-[dialog-overlay-hide_200ms]" />
>   <Dialog.Content className="fixed w-full max-w-md p-8 text-gray-900 -translate-x-1/2 -translate-y-1/2 bg-white rounded-md shadow left-1/2 top-1/2 data-[state=open]:animate-[dialog-content-show_200ms] data-[state=closed]:animate-[dialog-content-hide_200ms]">
>     <div className="flex items-center justify-between">
>       <Dialog.Title className="text-xl">{title}</Dialog.Title>
>       <Dialog.Close className="text-gray-400 hover:text-gray-500">
>         <Cross1Icon />
>       </Dialog.Close>
>     </div>
>     {children}
>   </Dialog.Content>
> </Dialog.Portal>
> ```
> 
> `Dialog` 모듈을 불러오고, 각각 모달(또는 버튼)의 검은 배경의 `Overlay`, 모달 그 자체인 `Content`와 하위 타이틀 `Title`, 축소 `Close` APi를 사용하면 됩니다. 이것들을 `Portal`로 감싸주면 RadixUI가 알아서 독립적인 div로 렌더링해주며, 개발자도구 > 요소를 눌러 확인해보면 DOM트리 중간에 생기는게 아니라 main과 동일한 레벨에 생겨 독립적으로 동작하도록 보장해줍니다(이건 정확하지 않을 수 있음).
> 
> 이 `Dialog` 모듈을 그대로 사용해도 전혀 무방하지만, 링크에 나오는 유튜버 개발자는 `Modal` 컴포넌트로 다시 추상화를 한 번 더 해 사용성을 극대화시켰습니다. 마치 이번 성민이형이 Game 컴포넌트를 디자인한 방식처럼(Game Object에 매핑한 방식) 추상화가 이뤄졌습니다.
> 
> ## Dialog -> Modal로 한 번 더 추상화하기
> ```tsx
> import * as Dialog from "@radix-ui/react-dialog";
> import { Cross1Icon } from "@radix-ui/react-icons";
> import { ReactNode } from "react";
> 
> export default function Modal({
>   open,
>   onOpenChange,
>   children,
> }: {
>   open?: boolean;
>   onOpenChange?: (open: boolean) => void;
>   children: ReactNode;
> }) {
>   return (
>     <Dialog.Root open={open} onOpenChange={onOpenChange}>
>       {children}
>     </Dialog.Root>
>   );
> }
> 
> function ModalContent({
>   title,
>   children,
> }: {
>   title: string;
>   children: ReactNode;
> }) {
>   return (
>     <Dialog.Portal>
>       <Dialog.Overlay className="fixed inset-0 bg-black/50 data-[state=open]:animate-[dialog-overlay-show_200ms] data-[state=closed]:animate-[dialog-overlay-hide_200ms]" />
>       <Dialog.Content className="fixed w-full max-w-md p-8 text-gray-900 -translate-x-1/2 -translate-y-1/2 bg-white rounded-md shadow left-1/2 top-1/2 data-[state=open]:animate-[dialog-content-show_200ms] data-[state=closed]:animate-[dialog-content-hide_200ms]">
>         <div className="flex items-center justify-between">
>           <Dialog.Title className="text-xl">{title}</Dialog.Title>
>           <Dialog.Close className="text-gray-400 hover:text-gray-500">
>             <Cross1Icon />
>           </Dialog.Close>
>         </div>
> 
>         {children}
>       </Dialog.Content>
>     </Dialog.Portal>
>   );
> }
> 
> Modal.Button = Dialog.Trigger;
> Modal.Content = ModalContent;
> Modal.Close = Dialog.Close;
> ```
> 
> 이 댓글에 위 유튜브 3부작 내용을 모두 이야기하기엔 지면이 좁기도 하고 저 또한 완전히 제 것이 아니기 때문에, 몇 가지 포인트만 말씀드리고 나머지는 유튜브 영상으로 대체하도록 하겠습니다. 2배속으로 재생하셔서 단순무식한 `data.map => li div button ~~` 컴포넌트가 마지막엔 디자인과 기능이 완전히 분리된 추상화 컴포넌트로 바뀌는 것을 꼭 보시기 바랍니다 ㅋㅋ
> 
> 위처럼 모달 컴포넌트를 작성해주면 아래 스샷에 나온 것처럼 아주 직관적으로 사용이 가능합니다. css class만 작성해주면 기능은 알아서 다 처리해주죠. ![image](https://user-images.githubusercontent.com/87803596/273579114-ee7b7ad6-769b-4ba2-b79e-cd7bb397a205.png)
> 
> 모달을 직접 만들려면 모달의 추상화 디자인 뿐만 아니라 정말 귀찮은 모달 토글 온오프 기능이나, 키보드로도 접근할 수 있게 하려면 별도의 키 매핑이 반드시 필요합니다. 이런 부분도 RadixUI 컴포넌트를 쓰면 무.료.로.해.줍.니.다. 정말 좋지 않나요?
> 
> 마지막으로 Radix의 좋은 점에 대해 정리하고 말을 줄이겠습니다. 글이 너무 길다면 유튭 영상 3부작 2배속으로 제발 한 번만 봐주세요. ㅋㅋ 진짜 좋아서 그럼
> 
> ## Radix의 좋은 점
> 1. Incremental adoption
>    모듈을 각각 adopt해와 번들 사이즈를 줄일 수 있다.
> 2. Unstyled
>    스타일은 없지만 Tag name으로 구분이 이미 돼있기 때문에 가독성이 매우 좋다
> 3. 키보드 상호작용 지원
>    별도의 세팅 없이도 WAI-ARIA 패턴에 맞게 키보드액션이 다 매핑돼있다.
> 4. 각 모듈마다 필요한 구성요소들이 준비돼있다
>    각 모듈마다 필요한 구성요소들이 이미 갖춰져있다. 모달의 경우 트리거(버튼), 포탈(모달) - 오버레이(검은화면), 컨텐트로 구성돼있고 심지어 오버레이를 갖다 쓰면 스크롤도 자동으로 막아준다!
> 5. Uncontrolled
>    Radix Component들은 이미 그 내장 기능을 통해 개발자가 control하지 않아도 되는 상태이다(uncontrolled). 하지만 local state를 생성해 얼마든지 개발자가 control할 수 있는 자유도가 있다(개편함)

ㅋㅋㅋㅋ정성이 대단합니다..

radix-ui에 대해서 이야기하는 걸 자주 들어본 적 있고, 컴포넌트가 어떻게 구성되어 있는지 살펴본 적도 있는데 꽤 잘 만들어져 있다고 생각했습니다. 우리가 모바일 퍼스트 웹사이트라서 모달을 사용해야 할 일이 많은데 좀 더 간편하게 사용할 수 있을 거 같아서 기대됩니다. 그리고 모듈을 각각 번들링하는 거 굉장히 야무집니다. 리팩토링 기간에 바로 써먹어봅시다. 레츠고!
