### ISSUE TITLE
[UI] 경기 하이라이트 영상 영역 추가

### ISSUE THREAD

**Issue by HiimKwak** [hufs-sports-live/client#20]
## 경기 하이라이트 영상이 노출될 영역 및 디자인 작성
- 고려해야할 점:
  - 경기 하이라이트 영상이 경기 사후에 업로드된다는 점: 영상 업로드 전까진 '이 곳에 경기 하이라이트 영상이 업로드 됩니다.' UI가 있어야 함
  - 관리자가 영상을 업로드하는 프로세스도 필요
    - 유튜브 영상을 훕스트리밍에 업로드하는 방식?

**Comment by HiimKwak** [comment]
## 1. 리액트-유튜브 라이브러리 사용하는 방법

참고 링크 : [[React] react-youtube로 유튜브 플레이어 삽입](https://velog.io/@soonmac/React-npm-react-youtube)

주요 API
```
<YouTube
  videoId={string}                  // defaults -> null
  id={string}                       // defaults -> null
  className={string}                // defaults -> null
  containerClassName={string}       // defaults -> ''
  title={string}                    // defaults -> null
  opts={obj}                        // defaults -> {}
  onReady={func}                    // defaults -> noop
  onPlay={func}                     // defaults -> noop
  onPause={func}                    // defaults -> noop
  onEnd={func}                      // defaults -> noop
  onError={func}                    // defaults -> noop
  onStateChange={func}              // defaults -> noop
  onPlaybackRateChange={func}       // defaults -> noop
  onPlaybackQualityChange={func}    // defaults -> noop
/>
```
* opts prop에 변수를 할당하는 경우 No overload matches this call 타입스크립트 오류가 발생하는 경우
  * 컴포넌트에 인라인으로 작성하니 오류가 발생하지 않았습니다.
* 유튜브 플레이어를 재생할 때 Indicate whether to send a cookie in a cross-site request by specifying its SameSite attribute 오류가 발생합니다.
  * 보안을 위해 도메인 간의 쿠키를 공유할 수 없고, 이를 해결하기 위해서는 쿠키 속성을 SameSite=None과 Secure 옵션을 같이 지정해야한다고 합니다.

**Comment by HiimKwak** [comment]
## 2. iframe API 사용하는 방법

참고 링크: [[Next.js] 유튜브 불러오기](https://jiyeongstar.tistory.com/196)

주요 API
```jsx
 function extractVideoID(url: string) {
    var regExp =
      /^.*((youtu.be\/)|(v\/)|(\/u\/\w\/)|(embed\/)|(watch\?))\??v?=?([^#\&\?]*).*/;
    var match = url.match(regExp);
    if (match && match[7].length == 11) {
      return match[7];
    } else {
      alert("Could not extract video ID.");
    }
  }
// 위의 코드를 통해 유튜브 영상 아이디를 찾아내어 변수로 저장

return(
...
 <iframe
    src={`https://www.youtube.com/embed/${videoId}`} 
    allowFullScreen
/>

...)
```
- `https://www.youtube.com/embed/${videoId}` 형태를 지켜야 함. 
  - 유튜브 url 복사는 `https://www.youtube.com/watch?v=${videoId}` 형태이고 
  - 공유 > 복사 의 경우 `https://youtu.be/${videoId}?si=???`
  - 공유 > 퍼가기 의 경우 `<iframe width="560" height="315" src="https://www.youtube.com/embed/${videoId}?si=????" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>` 이다.
-  공유 > 복사 일 때 나오는 url을 기준으로 파싱해서 삽입하는 방식으로 하는게 좋을 듯 하다(공유 > 복사가 모바일에서도 제일 편함 ㅇㅇ)

**Comment by seongminn** [comment]
video 넣어 뒀으니깐 이것도 이제 close 해도 될 듯 합니다.

근데 얘기해보고 싶은 건 유저는 유튜브 URL 복사할 때 id만 뽑아서 복사하지 않고 그냥 통째로 복사합니다.
`https://youtu.be/yt5_qRuxyfQ?si=rcsuj10QBtAnR7mz` 이렇게 말이죠.

그래서 값 넣을 때 id만 받는 게 아니라 주소 통째로 저장해서 프론트에서도 그냥 가져온 다음 유효성 검사 돌린 다음 만족하면
```js
return(
...
 <iframe
    src={videoUrl} 
    allowFullScreen
/>
```
이렇게 사용하는 게 어떤지요?
@HiimKwak
