### ISSUE TITLE
[REFACTOR] GAME 합성 컴포넌트를 context api를 활용하여 내부 로직 수정

### ISSUE THREAD

**Issue by seongminn** [hufs-sports-live/client#36]
[해당 영상](https://youtu.be/aAs36UeLnTg?si=56Gpe4ePmvcQTDr4)에서 소개하는 방법 중 첫 번째 방법을 참고했습니다.

현재 우리가 사용하는 `Game` 컴포넌트에서 관리하는 상태가 굉장히 많습니다.

- Game Label: 리그 이름
- Game Status: 현재 게임 상태
- Game Score: 게임 점수
- Game Team: 게임에 참여한 팀의 팀명(혹은 학과명)과 로고
- Game Timer: 게임 시작 시간

이 모든 값을 일일이 분기 태우고 렌더링 할 지 말 지 결정해주는 일은 너무 명령적이기 때문에 코드의 복잡성이 커진다는 문제가 있습니다.

그런데 잘 보면, Game 컴포넌트에서 사용하는 값들은 모두 API 응답 이후 별도의 변경이 필요하지 않은 값이라는 것을 알 수 있습니다. 그래서 응답 값을 그대로 넣어주고 이를 Game 컴포넌트 내부에서 Context API로 필요한 곳에서 사용하고 싶은 값만 꺼내 쓸 수 있도록 하는 방법을 생각해봤습니다. 대략적으로 이해할 수 있도록 실제 코드와 비슷한 의사 코드로 작성하니 이 점 양해해주세요.

```tsx
const GameContext = createContext({
    name: '',
    firstTeam: { firstTeam.logo: '', firstTeam.name: '' }
    score: { firstTaemScore: 0 }
    time: ''
    // 등등..
})

export defulat function GameWrapper(game: GameType, children) {
    const contextValue = game

    return <GameContext.Provider value={contextValue}>{children}</GameContext>
}

// GameStatus.tsx
export default function GameStatus(gameState) {
    // 게임 상태 관련한 문자열은 상수로 빼는 것이 좋겠습니다.
    retirm <div>{GAME_STATUS[gameState]}</div>
}
```

이런 식으로 작성이 될 것 같고, 사용하는 곳에서는 이렇게 쓰면 될 것 같습니다.

```tsx
export default function Component() {
    // API 호출
    const gameData = getGameData()

    return (
        // GameWrapper에 데이터를 모조리 모아 놓고 하위 컴포넌트에서는 스타일만 관리해주면 됩니다.
        <Game {...gameData}>
            <Game.Label className="style" />
            <Game.Team className="style" />
            <Game.Score className="style" />
        </Game>
}
```

이런 식으로 이제는 필요한 곳에서 사용할 컴포넌트를 추가만 해주고 스타일만 먹여주면 컴포넌트 내부에서 어떤 값을 렌더링 할 지 알아서 결정해주기 때문에 보다 선언적으로 컴포넌트를 사용할 수 있습니다. 또 스타일과 로직의 관심사를 분리할 수 있다는 점에서 유지 보수에도 굉장히 용이해질 것 같네요.

다만 걱정되는 것은, 현재 디자인이 

> 첫 번째 팀 | 스코어 | 두 번째 팀

이런 식이기 때문에 첫 번째 팀, 두 번째 팀 컴포넌트를 따로 추가하는 방식을 사용해야 할 것 같네요. 컴포넌트를 재사용하면 되기 때문에 크게 문제가 될 것 같지는 않지만, 그래도 디자인이 나오면 어떻게 어떤 식으로 사용해야 할 지 생각해보고, 필요하다면 디자인을 수정하는 방법도 같이 고민해보면 좋을 것 같습니다.

해당 내용에 대해서 어떻게 생각하시나요? @HiimKwak

**Comment by HiimKwak** [comment]
캬~ 이런 좋은 영상이 있었다니 우리의 그간의 고민들을 일목요연하게 정리해주는 좋은 자료 찾아주셔서 감사합니다.

contextAPI를 사용해서 명령형 컴포넌트를 선언적으로 바꾸는 방식은 아주 좋은 방식이라 생각합니다. 무엇보다 말씀하신 것처럼 일일이 value를 넘겨주지 않아도 알아서 컨텍스트 안에서 렌더링할 값들을 분배하는게 말그대로 '혁 신 적'이네요.

> 이런 식이기 때문에 첫 번째 팀, 두 번째 팀 컴포넌트를 따로 추가하는 방식을 사용해야 할 것 같네요. 
이 부분은 지금 제가 생각하기로는 Game.Team 컴포넌트에 따로 'order' 혹은 'side'란 이름의 2진 플래그 프로퍼티를 하나 만들어서 'order={first / second}' 혹은 'side={blue / red}'로 넘겨주어 두번째 팀 컴포넌트를 따로 만들 필요 없이 2진 플래그로 첫번째 팀을 렌더링할지 두번째 팀을 렌더링하게 할지 결정해주면 어떨까요?

그리고 또 하나 질문이 있는데요, 아래 영상에서 나왔던 '자식 컴포넌트들을 부모 컴포넌트의 프로퍼티로 등록한다.' 부분이
![image](https://github.com/hufs-sports-live/client/assets/87803596/1efa8fe6-347a-41ae-b0cc-13e8fcfe5c86)
저희 Game 컴포넌트에서는 GameMain 컴포넌트에서 각 자식 컴포넌트의 타입과 일치한 녀석들을 필터링해주고 Object.assign 메소드를 써서 바인딩해주고 있잖아요? 이 부분은 영상처럼 단순하게 `InputWrapper.Input = Input;` 이런 식으로 바인딩하는 것과 어떤 차이가 있는건가요? 지금 드는 생각은 저희 Game 컴포넌트처럼 검사해주는 방식이 당연히 안정성이 더 높겠다는 생각은 있지만 굳이 그 과정을 거쳐야할 정도로 컴포넌트 간 무결성이 위협받는 상황이 있는가에 대해서는 의문이 듭니다. 설명 부탁드립니다!

**Comment by seongminn** [comment]
질문을 잘 이해하지 못한 것 같아서 간단하게 코멘트 남깁니다!

현재 GameMain 컴포넌트에서 타입에 맞는 요소들을 필터링하는 작업은 '자식 컴포넌트를 부모 컴포넌트의 프로퍼티로 등록한다'는 작업과는 무관합니다. 그리고 Object.assign 메서드를 사용하는 것과 Wrapper 컴포넌트의 프로퍼티에 하위 컴포넌트를 직접 등록하는 방법도 둘 다 GameMain 컴포넌트의 프로퍼티에 하위 컴포넌트에 대한 참조를 동일하게 할당하고 있기 때문에 결국 똑같은 동작을 합니다. 그래서 두 방법 중 어떤 것을 사용하는지는 우리가 결정하기 나름일 것 같네요!

제가 질문을 제대로 이해하지 못한 것이라면 추가 설명을 조금 남겨주시면 감사하겠습니다!

**Comment by HiimKwak** [comment]
아닙니다 제 개떡같은 말을 제대로 해석해주셨네요 Object.assign이랑 직접 하위컴포넌트 등록하는거랑 똑같은 동작이라면 건드리지 않는게 좋은 것 같습니다 감사합니다 ㅎㅎ
