### ISSUE TITLE
[REFACTOR] Tailwindcss 사용성 향상

### ISSUE THREAD

**Issue by seongminn** [hufs-sports-live/client#47]
### 문제

왜인지 모르겠는데, 사용하기로 했던 확장 프로그램(tailwindcss 클래스 순서 정렬)이 로컬에서 동작하지 않습니다. 

### 제안

그래서 원인을 찾아보던 중, tailwindcss에서 권장하는 prettier 플러그인을 발견했습니다. tailwindlabs에서 직접 정한 정렬 순서에 따라 클래스 순서를 정렬해주기 때문에 보다 신뢰할 수 있고, prettier 플러그인을 사용하기 때문에 확장 프로그램을 사용하는 것보다 더 강력하게 컨벤션을 유지할 수 있을 것 같습니다. 주간 다운로드 수도 100만 이상이고, 업데이트도 자주 이뤄지는 것 같아서 충분히 사용할만 한 것 같습니다.

https://github.com/tailwindlabs/prettier-plugin-tailwindcss

이러한 이유로 `prettier-plugin-tailwindcss` 사용을 제안합니다.

**참고**

https://www.npmjs.com/package/eslint-plugin-tailwindcss

이런 eslint 플러그인도 있네요. 

- 클래스 정렬 순서 커스텀
- 충돌하는 className 사용 방지(`bg-blue` + `bg-red` 등)
- 사용자 정의 클래스 방지(`.header`, `.game` 등)
- 프로젝트에 정의되지 않은 클래스 방지

해당 플러그인의 경우에는 tailwindcss에서 따로 언급하고 있지는 않기 때문에 같이 이야기해보면 좋을 것 같아 첨부합니다.

### 문제

tailwindcss는 클래스명을 뒤쪽에 쓴다고 해도 합병하지 않습니다. 하지만 우리는 컴포넌트 기본 스타일을 내부에서 정의하고, 일부 스타일을 외부에서 주입 받기 때문에 클래스 합병을 사용할 일이 발생합니다.

### 제안

`tailwind-merge`와 `clsx` 조합으로 해결할 수 있습니다. `tailwind-merge`는 기존에 정의되어 있던 클래스를 주입 받은 클래스명으로 오버라이딩 할 수 있도록 합니다.

`clsx`는 className을 조건적으로 사용하는 데에 도움을 주는 라이브러리라고 합니다.

```ts
import type { ClassValue } from 'clsx'
import { clsx } from 'clsx'
import { twMerge } from 'tailwind-merge'

export function cn(...inputs: ClassValue[]) {
  return twMerge(clsx(inputs))
}
```

이런 식으로 유틸 함수를 지정해놓고 사용하면 좋을 듯 합니다.

어떻게 생각하시나요? @HiimKwak

**Comment by HiimKwak** [comment]
좋습니다. eslint 플러그인도 좋아보이지만 prettier 플러그인으로도 충분할 것 같다는 생각입니다.

tailwind-merge도 찬성합니다. 바로 도입해주시면 좋을 것 같아요!
