### ISSUE TITLE
[STYLE] 디자인 확정 관련 설정

### ISSUE THREAD

**Issue by HiimKwak** [hufs-sports-live/client#56]
## 컬러 팔레트 추가

디자인이 어느정도 윤곽이 나온 관계로 컬러 팔레트를 추가해놓고자 합니다.

```js
theme: {
  extend: {
    colors: {
      // gray: {
      //   light: '#EFEFEF',
      //   DEFAULT: '#D9D9D9',
      //   heavy: '#8C8C8C',
      // },
      blue: {
      100: "#D9DEFE",
      200: "#B4BDFD",
      300: "#8E9BFA",
      400: "#717FF6",
      DEFAULT: "#4354F0",
      600: "#303ECE",
      700: "#212CAC",
      800: "#151D8B",
      900: "#0C1273",
      },
    }
  }
}
```

blue의 경우 아래 9단계 컬러를 사용하면 될 것 같고, [DEFAULT](https://tailwindcss.com/docs/customizing-colors#using-the-default-colors:~:text=Tailwind%2C%20the%20special-,DEFAULT,-key%20can%20be) 옵션으로 500 레벨을 설정해 `bg-blue`만 했을 때 디폴트 컬러가 반영되도록 하면 좋을 것 같습니다.
![image](https://github.com/hufs-sports-live/client/assets/87803596/1c7f441c-1ec9-405f-b2dd-4bd1405746bb)
gray 컬러의 경우 [슬랙 디자인 피드백에 제가 남긴 댓글](https://w1698251905-8dk231342.slack.com/archives/C0632KV5M6J/p1700061942131089?thread_ts=1700029825.444979&cid=C0632KV5M6J)처럼 전체적으로 회색이 너무 많이 들어가 초기에 우리가 지향했던 가볍고 산뜻한 느낌이 사라졌다고 판단해 피드백을 요청한 상태입니다. 따라서 피드백을 받았을 때 gray컬러의 조정이 있을 것 같아 주석처리해놨고 우선 적용하게 된다면 blue컬러만 설정해놓으면 될 것 같습니다.

해당 팔레트 설정에 대해 어떤 생각이신가요? 우선은 9레벨로 만들어봤습니다만 더 자주 사용하는 3레벨(light, DEFAULT, heavy)로만 줄여도 좋고, colors말고도 다른 프로퍼티 설정도 필요하다 생각하시면 말씀해주시면 좋겠습니다.

## 아이콘 관련

우리 서비스에 많은 아이콘들이 사용되는건 아니지만 햄버거, 크로스 그리고 휴지통 아이콘은 사용되고 있습니다.

그 외에 아이콘이 사용될 여지가 많진 않은 것 같아서, 아이콘 사용에 대해 고민을 해보았습니다.

1. [Radix-ui/icons](https://www.radix-ui.com/icons) 사용하기
해당 라이브러리는 아이콘이 몇 개 없습니다. 필수적인 아이콘만 있어서 react icons 라이브러리를 설치하는 것보다 가벼울 것으로 예상해 골라보았습니다.
2. 라이브러리 설치하지 말고 아이콘 에셋 직접 저장해서 쓰기
아이콘 사용처가 많지 않은 만큼 라이브러리조차 낭비라고 판단될 경우에 2번처럼 진행해도 괜찮을 것 같습니다.
2번을 채택할 경우 에셋 저장 위치(public or src), 에셋 확장자(png, webp or svg) 등의 추가 고려 요소도 정해야 합니다.

이에 대한 의견 또는 더 좋은 방법이 있으면 말씀 부탁드립니다.

**Comment by seongminn** [comment]
1. 9레벨은 솔직히 다 안 쓸 거 같아서 3레벨도 충분하다고 생각합니당 어떻게 생각하시나요?
2. 지금 수준에서 아이콘은 직접 에셋 추가하는 게 좋다고 생각합니다. 디자인 보니까 딱히 사용되는 아이콘이 많지는 않은 거 같아서요!
3. 그리고 햄버거 아이콘 같은 경우 동적인 효과를 추가하고 싶으면 CSS로 하는 것도 좋아보이긴 합니다. 이건 뭐 기획이 나온 게 아니니까 취향대로 하시지요!

**Comment by HiimKwak** [comment]
> 1. 9레벨은 솔직히 다 안 쓸 거 같아서 3레벨도 충분하다고 생각합니당 어떻게 생각하시나요?
좋습니다 그럼 3단계로 줄여서 light DEFAULT heavy로 가겠습니다

> 2. 지금 수준에서 아이콘은 직접 에셋 추가하는 게 좋다고 생각합니다. 디자인 보니까 딱히 사용되는 아이콘이 많지는 않은 거 같아서요!
좋습니다 그럼 확장자는 선호하시는 확장자가 있을까요? 저장 위치는 어디로 하는게 좋을까요?

> 3. 그리고 햄버거 아이콘 같은 경우 동적인 효과를 추가하고 싶으면 CSS로 하는 것도 좋아보이긴 합니다. 이건 뭐 기획이 나온 게 아니니까 취향대로 하시지요!
햄버거 아이콘 자체에 애니메이션을 넣는건 지금은 불필요한 것 같습니다. 나중에 고려해보면 좋을 것 같습니다!

**Comment by seongminn** [comment]
아이콘 위치는 `public/icons/`에 저장하면 좋을 것 같습니다.
아이콘 확장자는 `svg`가 좋을 것 같습니다.

**Comment by HiimKwak** [comment]
지금 아이콘 찾아보고 있는데, radix ui icon에서 제공하는 svg파일이 있어서 일단 다운로드 해놨습니다.

그런데 살짝 아쉬운게 아이콘들이 조금 얇쌍해서 그부분이 거슬리네요. 그렇다고 svg 아이콘 사이트(flaticon 등)에서 일일이 찾아 쓰는건 통일성이 없어서 꺼려지구요. 통일성을 위해 radix icon을 쓸까요?
![cross-2](https://github.com/hufs-sports-live/client/assets/87803596/2f5fe604-77e5-45bb-aa7e-c8d60ee0c313)

**Comment by seongminn** [comment]
![essential-1](https://github.com/hufs-sports-live/client/assets/88662637/c7acae5f-79cb-4a13-9381-e925af91c500)
![list](https://github.com/hufs-sports-live/client/assets/88662637/498e4c4b-4342-481f-9f49-d49817e69a9e)
![essential](https://github.com/hufs-sports-live/client/assets/88662637/1d789ff2-0038-4f1c-9b2e-a98ce12c33c6)

저는 이런 것도 괜찮다고 생각합니다. 피그마 디자인 시스템 찾아보면 이런 기본적인 아이콘들은 웬만하면 포함하고 있으니 맘에 들지 않는다면 피그마에서 더 찾아보는 것도 좋아보입니다

**Comment by HiimKwak** [comment]
흠, 그냥 피그마 디자인에 그려져있는 애들을 svg로 export해서 사용하는게 가장 손실이 없는 방안같습니다. 따로 아이콘 찾지 않아도 되구요. export할 요소들은 '2차 UI' 박스 안에 제가 따로 빼서 정리해뒀고 PR 올릴 때 리스트업하겠습니다!
